SCREEN_TITLE = "Journey to the Moon"
PLAYER_SCALING = 1
GRAVITY = 1
PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 20

SPRITE_NATIVE_SIZE = 128
SPRITE_SCALING = 1
SPRITE_SIZE_WIDTH = 128 #int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
SPRITE_SIZE_HEIGHT = 126 #int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
SPRITE_IDLE_FRAMES = 38 #legacy unity template value
SPRITE_RUN_FRAMES = 29
SPRITE_SPAWN_FRAMES = 20
SPRITE_SCALING_BOX=1
TILE_SCALING=1

LEFT_FACING = 0
RIGHT_FACING = 1
CHARACTER_SCALING = 1
TILE_SCALING = 0.5
BOX_WIDTH=400
BOX_HEIGHT=50
