import pathlib
import arcade

SCREEN_TITLE = "Journey to the Moon"
GRAVITY = 1
PLAYER_MOVEMENT_SPEED = 5
PLAYER_SUPER_JUMP_SPEED = 40
PLAYER_REGULAR_JUMP_SPEED = 30

SPRITE_NATIVE_SIZE_WIDTH = 128
SPRITE_NATIVE_SIZE_HEIGHT = 126
SPRITE_SCALING = 1
SPRITE_SIZE_WIDTH = int(SPRITE_NATIVE_SIZE_WIDTH * SPRITE_SCALING)
SPRITE_SIZE_HEIGHT = int(SPRITE_NATIVE_SIZE_HEIGHT * SPRITE_SCALING)
SPRITE_IDLE_FRAMES = 38 #legacy unity template value
SPRITE_RUN_FRAMES = 29
SPRITE_CLIMB_FRAMES = 10
SPRITE_SPAWN_FRAMES = 20
SPRITE_JUMP_FRAMES = 49
SPRITE_DEATH_FRAMES = 15
SPRITE_SCALING_BOX=1
TILE_SCALING=1

COIN_SCALING = 0.7

LEFT_FACING = 0
RIGHT_FACING = 1
CHARACTER_SCALING = 1
TILE_SCALING = 0.5

STATUS_BAR_ITEM_BOX_WIDTH=300
STATUS_BAR_ITEM_BOX_HEIGHT=50
STATUS_BAR_MENU_ITEM_WIDTH=290
STATUS_BAR_MENU_ITEM_HEIGHT=50


DOGE_DATA_HUB_ONLINE=True

DOGE_DATA_HUB_CALLING_INTERVAL=5
TRANSLUCENT_BACKGROUND_COLOR = (0, 0, 0, 128)

ASSETS_PATH = pathlib.Path(__file__).resolve().parent.parent.parent / "assets"            
DOGE_DATA_SERVICE_URL = "http://localhost:5000/currentPrice"
PLAY_MUSIC_ON_START = False
INITIAL_MUSIC_VOLUME = 0.5
SOUND_ON = True
SOUND_ON_VOLUME = 0.8

SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SCALING

PLAYER_START_X = 300
PLAYER_START_Y = 7000

# Layer Names from the included python arcade 2.6.17 resource TileMap 
LAYER_NAME_PLATFORMS = "Platforms"
LAYER_NAME_MOVING_PLATFORMS = "Moving Platforms"
LAYER_NAME_COINS = "Coins"
LAYER_NAME_FOREGROUND = "Foreground"
LAYER_NAME_BACKGROUND = "Background"
LAYER_NAME_DONT_TOUCH = "Don't Touch"
LAYER_NAME_LADDERS = "Ladders"

IS_RAINING = True
IS_SNOWING = False
IS_TOO_HOT = False

TRIGGER_CONFETTI = True
CONFETTI_COUNT = 15
COLORS = [arcade.color.RED, arcade.color.GREEN, arcade.color.BLUE, 
          arcade.color.YELLOW, arcade.color.ORANGE, arcade.color.PURPLE, 
          arcade.color.CYAN, arcade.color.MAGENTA]

RAINDROP_COUNT = 50


# PS4 Controller Button Mappings
BUTTON_SQUARE = 0
BUTTON_X = 1
BUTTON_CIRCLE = 2
BUTTON_TRIANGLE = 3
BUTTON_L1 = 4
BUTTON_R1 = 5
BUTTON_L2 = 6
BUTTON_R2 = 7
BUTTON_SHARE = 8
BUTTON_OPTIONS = 9
BUTTON_L3 = 10
BUTTON_R3 = 11
BUTTON_PS = 12
BUTTON_TOUCHPAD = 13

# PS4 Controller Axis Mappings
AXIS_LEFT_STICK_X = 0
AXIS_LEFT_STICK_Y = 1
AXIS_RIGHT_STICK_X = 2
AXIS_RIGHT_STICK_Y = 5
AXIS_L2_TRIGGER = 3
AXIS_R2_TRIGGER = 4

# D-Pad (Hat Switch) Values
# Note: The D-Pad values depend on how the library reports Hat Switch states.
# I might need to adjust these based on future testing.
DPAD_UP = (0, 1)
DPAD_DOWN = (0, -1)
DPAD_LEFT = (-1, 0)
DPAD_RIGHT = (1, 0)
DPAD_CENTER = (0, 0)

WINDOW_PERFORMANCE_METRICS = True
LOAD_VERTICAL_MAPS = True
