import pathlib

SCREEN_TITLE = "Journey to the Moon"
#PLAYER_SCALING = 1
GRAVITY = 1
PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 20

SPRITE_NATIVE_SIZE_WIDTH = 128
SPRITE_NATIVE_SIZE_HEIGHT = 126
SPRITE_SCALING = 1
SPRITE_SIZE_WIDTH = int(SPRITE_NATIVE_SIZE_WIDTH * SPRITE_SCALING)
SPRITE_SIZE_HEIGHT = int(SPRITE_NATIVE_SIZE_HEIGHT * SPRITE_SCALING)
SPRITE_IDLE_FRAMES = 38 #legacy unity template value
SPRITE_RUN_FRAMES = 29
SPRITE_SPAWN_FRAMES = 20
SPRITE_SCALING_BOX=1
TILE_SCALING=1

LEFT_FACING = 0
RIGHT_FACING = 1
CHARACTER_SCALING = 1
TILE_SCALING = 0.5

STATUS_BAR_ITEM_BOX_WIDTH=300
STATUS_BAR_ITEM_BOX_HEIGHT=50
STATUS_BAR_MENU_ITEM_WIDTH=290
STATUS_BAR_MENU_ITEM_HEIGHT=50


DOGE_DATA_HUB_ONLINE=True
DOGE_DATA_HUB_CALLING_INTERVAL=5
TRANSLUCENT_BACKGROUND_COLOR = (0, 0, 0, 128)

ASSETS_PATH = pathlib.Path(__file__).resolve().parent.parent.parent / "assets"            
